#CREATE DOCKER IMAGE
version: "3.8"
services: 
  dev-database:
    image: postgres:15.0
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: nestjs
    networks:
      - nestjs-network
networks:
  nestjs-network:

#create container, network, ... from "docker compose" file:
#docker compose up -d